### ISSUE TITLE
Client could not parse the value, it expects a number

### ISSUE THREAD

**Issue by danielfrg** [polyaxon/polyaxon-helper#2]
I am getting this error when running the mnist example. 

Probably something that it changed between versions?

```
master.1 -- Traceback (most recent call last):
master.1 -- File "run.py", line 60, in <module>
master.1 -- test(model=model, test_loader=test_loader, cuda=args.cuda)
master.1 -- File "/code/train.py", line 83, in test
master.1 -- send_metrics(loss=test_loss, accuracy=accuracy)
master.1 -- File "/opt/conda/lib/python3.6/site-packages/polyaxon_helper/__init__.py", line 93, in send_metrics
master.1 -- experiment.log_metrics(**metrics)
master.1 -- File "/opt/conda/lib/python3.6/site-packages/polyaxon_client/tracking/experiment.py", line 181, in log_metrics
master.1 -- background=True)
master.1 -- File "/opt/conda/lib/python3.6/site-packages/polyaxon_client/api/experiment.py", line 215, in create_metric
master.1 -- json_data = {'values': {key: parse_numbers(values[key]) for key in values}}
master.1 -- File "/opt/conda/lib/python3.6/site-packages/polyaxon_client/api/experiment.py", line 215, in <dictcomp>
master.1 -- json_data = {'values': {key: parse_numbers(values[key]) for key in values}}
master.1 -- File "/opt/conda/lib/python3.6/site-packages/polyaxon_client/api/experiment.py", line 213, in parse_numbers
master.1 -- 'Client could not parse the value `{}`, it expects a number.'.format(value))
master.1 -- polyaxon_client.exceptions.PolyaxonClientException: Client could not parse the value `0.09415460377931595`, it expects a number.
```

**Comment by mouradmourafiq** [comment]
I am not sure, I will try it and let you know. I should add e2e testing for the examples as well to detect this errors.

**Comment by danielfrg** [comment]
Ok, I don't think this is a bug. I think it something in pytorch changed so it returns a `torch.Tensor` that the client lib is expecting so I might just need to modify the example to return a float.

**Comment by danielfrg** [comment]
Ok, I fixed it with: https://github.com/polyaxon/polyaxon-examples/pull/1

Not a bug on this side but probably would be nice to update the `parse_numbers` as you mention.
